<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Seller extends Model
{
    public const COLUMN_MAP = [
        'seller_id' => 'seller_id',
        'Источники баз' => 'source_bases',
        'Ссылка на продавца' => 'seller_url',
        'Торговое название' => 'trade_name',
        'Название сделки' => 'deal_name',
        'Категория товаров' => 'product_category',
        'Наименование организации на Wildberries' => 'wb_organization_name',
        'Мобильные телефоны компании' => 'company_mobile_phones',
        'Стационарные телефоны компании' => 'company_landline_phones',
        'Электронная почта компании' => 'company_email',
        'Сайт компании' => 'company_website',
        'whatsapp' => 'whatsapp',
        'telegram' => 'telegram',
        'viber' => 'viber',
        'vk' => 'vk',
        'instagram' => 'instagram',
        'ok' => 'ok',
        'Рейтинг' => 'rating',
        'Количество отзывов' => 'reviews_count',
        'Товаров продано' => 'sold_products_count',
        '% выкупленных товаров' => 'buyout_percent',
        'Скорость продаж (товаров в день)' => 'sales_speed_per_day',
        'Адрес продавца' => 'seller_address',
        'Дата регистрации на платформе' => 'platform_registered_at',
        'ОГРН' => 'ogrn',
        'ИНН' => 'inn',
        'Краткое наименование' => 'short_name',
        'ФИО руководителя' => 'director_full_name',
        'Должность руководителя' => 'director_position',
        'Главный код ОКВЭД' => 'main_okved_code',
        'Наименование главного ОКВЭД' => 'main_okved_name',
        'Дата регистрации' => 'registered_at',
        'Дата ликвидации' => 'liquidated_at',
        'Статус компании' => 'company_status',
        'Раздел товаров' => 'product_section',
        'Профиль на сайте Wildberries' => 'wb_profile_url',
        'Категории товаров' => 'product_categories',
        'Бренды' => 'brands',
        'Название магазина на Wildberries' => 'wb_store_name',
        'Телефоны мобильные' => 'mobile_phones',
        'Телефоны городские' => 'landline_phones',
        'Email' => 'email',
        'Сайт' => 'website',
        'Ссылка на первый в списке товар продавца' => 'first_product_url',
        'Рейтинг продавца' => 'seller_rating',
        '% выкупленных заказов' => 'orders_buyout_percent',
        'Количество товаров в продаже на дату сбора данных' => 'products_in_stock_count',
        'Адрес организации на Wildberries' => 'wb_organization_address',
        'Регистрация на Wildberries' => 'wb_registration_at',
        'Юридический адрес' => 'legal_address',
        'Название продавца на Wildberries' => 'wb_seller_name',
        'Рабочие телефоны мобильные' => 'work_mobile_phones',
        'Рабочие телефоны мобильные дополнение по юр лицам' => 'work_mobile_phones_legal_extra',
        'Рабочие телефоны городские' => 'work_landline_phones',
        'Рабочие телефоны городские дополнение по юр лицам' => 'work_landline_phones_legal_extra',
        'Рабочие Email' => 'work_emails',
        'Рабочие Email дополнительный источник' => 'work_emails_extra_source',
        'Сайт дополнение' => 'website_extra',
        'Whatsapp' => 'work_whatsapp',
        'Whatsapp дополнение по юр лицам' => 'work_whatsapp_legal_extra',
        'Telegram' => 'work_telegram',
        'VK' => 'work_vk',
        'VK дополнительный источник' => 'work_vk_extra_source',
        'Instagram' => 'work_instagram',
        'OK' => 'work_ok',
        'OK дополнительный источник' => 'work_ok_extra_source',
        'Среднее количество продаваемых товаров в день' => 'avg_sold_products_per_day',
        'Страница на сайте Wildberries' => 'wb_page_url',
        'Телефоны мобильные рабочие' => 'working_mobile_phones',
        'Телефоны городские рабочие' => 'working_landline_phones',
        'Email рабочий' => 'working_email',
        'Проданных товаров' => 'sold_products',
        'Дата регистрации на Wildberries' => 'wildberries_registered_at',
        'Статус организации' => 'organization_status',
        'Дата регистрации в ФНС' => 'fns_registered_at',
        'Адрес' => 'address',
        'Регион' => 'region',
        'Вид деятельности' => 'activity_type',
    ];

    protected $fillable = [
        'seller_id',
        'source_bases',
        'seller_url',
        'trade_name',
        'deal_name',
        'product_category',
        'wb_organization_name',
        'company_mobile_phones',
        'company_landline_phones',
        'company_email',
        'company_website',
        'whatsapp',
        'telegram',
        'viber',
        'vk',
        'instagram',
        'ok',
        'rating',
        'reviews_count',
        'sold_products_count',
        'buyout_percent',
        'sales_speed_per_day',
        'seller_address',
        'platform_registered_at',
        'ogrn',
        'inn',
        'short_name',
        'director_full_name',
        'director_position',
        'main_okved_code',
        'main_okved_name',
        'registered_at',
        'liquidated_at',
        'company_status',
        'product_section',
        'wb_profile_url',
        'product_categories',
        'brands',
        'wb_store_name',
        'mobile_phones',
        'landline_phones',
        'email',
        'website',
        'first_product_url',
        'seller_rating',
        'orders_buyout_percent',
        'products_in_stock_count',
        'wb_organization_address',
        'wb_registration_at',
        'legal_address',
        'wb_seller_name',
        'work_mobile_phones',
        'work_mobile_phones_legal_extra',
        'work_landline_phones',
        'work_landline_phones_legal_extra',
        'work_emails',
        'work_emails_extra_source',
        'website_extra',
        'work_whatsapp',
        'work_whatsapp_legal_extra',
        'work_telegram',
        'work_vk',
        'work_vk_extra_source',
        'work_instagram',
        'work_ok',
        'work_ok_extra_source',
        'avg_sold_products_per_day',
        'wb_page_url',
        'working_mobile_phones',
        'working_landline_phones',
        'working_email',
        'sold_products',
        'wildberries_registered_at',
        'organization_status',
        'fns_registered_at',
        'address',
        'region',
        'activity_type',
        'lead_id',
        'contact_id',
        'company_id',
        'is_exported',
    ];

    protected function casts(): array
    {
        return [
            'rating' => 'decimal:2',
            'reviews_count' => 'integer',
            'sold_products_count' => 'integer',
            'buyout_percent' => 'decimal:2',
            'sales_speed_per_day' => 'decimal:2',
            'platform_registered_at' => 'date',
            'registered_at' => 'date',
            'liquidated_at' => 'date',
            'seller_rating' => 'decimal:2',
            'orders_buyout_percent' => 'decimal:2',
            'products_in_stock_count' => 'integer',
            'wb_registration_at' => 'date',
            'avg_sold_products_per_day' => 'decimal:2',
            'sold_products' => 'integer',
            'wildberries_registered_at' => 'date',
            'fns_registered_at' => 'date',
            'lead_id' => 'integer',
            'contact_id' => 'integer',
            'company_id' => 'integer',
            'is_exported' => 'boolean',
        ];
    }
}
